2019-04-26 11:50:55,914 ERROR 38516 [-/127.0.0.1/-/6ms POST /api/v2/users/login] nodejs.TypeError: Cannot read property 'name' of undefined
    at UserController.login (G:\self-practice\hen-demo\app\controller\v2\user.js:39:27)
    at Object.callFn (G:\self-practice\hen-demo\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (G:\self-practice\hen-demo\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (G:\self-practice\hen-demo\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (G:\self-practice\hen-demo\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (G:\self-practice\hen-demo\node_modules\koa-compose\index.js:44:32)
    at next (G:\self-practice\hen-demo\node_modules\koa-compose\index.js:45:18)
    at G:\self-practice\hen-demo\node_modules\@eggjs\router\lib\router.js:190:18
    at dispatch (G:\self-practice\hen-demo\node_modules\koa-compose\index.js:44:32)
    at G:\self-practice\hen-demo\node_modules\koa-compose\index.js:36:12

pid: 38516
hostname: pc1-hz20065563

2019-04-26 11:52:20,469 ERROR 38516 [-/127.0.0.1/-/0ms POST /api/v2/users/login] nodejs.TypeError: Cannot read property 'name' of undefined
    at UserController.login (G:\self-practice\hen-demo\app\controller\v2\user.js:39:27)
    at Object.callFn (G:\self-practice\hen-demo\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (G:\self-practice\hen-demo\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (G:\self-practice\hen-demo\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (G:\self-practice\hen-demo\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (G:\self-practice\hen-demo\node_modules\koa-compose\index.js:44:32)
    at next (G:\self-practice\hen-demo\node_modules\koa-compose\index.js:45:18)
    at G:\self-practice\hen-demo\node_modules\@eggjs\router\lib\router.js:190:18
    at dispatch (G:\self-practice\hen-demo\node_modules\koa-compose\index.js:44:32)
    at G:\self-practice\hen-demo\node_modules\koa-compose\index.js:36:12

pid: 38516
hostname: pc1-hz20065563

2019-04-26 12:35:25,817 ERROR 25096 nodejs.ClusterClientNoResponseError: client no response in 92600ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (G:\self-practice\hen-demo\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 25096
hostname: pc1-hz20065563

2019-04-26 12:39:10,622 ERROR 25096 nodejs.ClusterClientNoResponseError: client no response in 84798ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (G:\self-practice\hen-demo\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 25096
hostname: pc1-hz20065563

2019-04-26 12:43:00,913 ERROR 25096 nodejs.ClusterClientNoResponseError: client no response in 89678ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (G:\self-practice\hen-demo\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 25096
hostname: pc1-hz20065563

2019-04-26 12:47:50,920 ERROR 25096 nodejs.ClusterClientNoResponseError: client no response in 89996ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (G:\self-practice\hen-demo\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 25096
hostname: pc1-hz20065563

2019-04-26 12:51:39,577 ERROR 25096 nodejs.ClusterClientNoResponseError: client no response in 88647ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (G:\self-practice\hen-demo\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 25096
hostname: pc1-hz20065563

2019-04-26 12:55:31,188 ERROR 25096 nodejs.ClusterClientNoResponseError: client no response in 91604ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (G:\self-practice\hen-demo\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 25096
hostname: pc1-hz20065563

2019-04-26 12:59:20,580 ERROR 25096 nodejs.ClusterClientNoResponseError: client no response in 89384ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (G:\self-practice\hen-demo\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 25096
hostname: pc1-hz20065563

2019-04-26 13:03:10,737 ERROR 25096 nodejs.ClusterClientNoResponseError: client no response in 90134ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (G:\self-practice\hen-demo\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 25096
hostname: pc1-hz20065563

2019-04-26 13:08:30,603 ERROR 25096 nodejs.ClusterClientNoResponseError: client no response in 99854ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (G:\self-practice\hen-demo\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 25096
hostname: pc1-hz20065563

2019-04-26 13:12:20,886 ERROR 25096 nodejs.ClusterClientNoResponseError: client no response in 89662ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (G:\self-practice\hen-demo\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 25096
hostname: pc1-hz20065563

2019-04-26 13:16:10,895 ERROR 25096 nodejs.ClusterClientNoResponseError: client no response in 89998ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (G:\self-practice\hen-demo\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 25096
hostname: pc1-hz20065563

2019-04-26 13:20:02,126 ERROR 25096 nodejs.ClusterClientNoResponseError: client no response in 91224ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (G:\self-practice\hen-demo\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 25096
hostname: pc1-hz20065563

2019-04-26 13:24:22,917 ERROR 25096 nodejs.ClusterClientNoResponseError: client no response in 100782ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (G:\self-practice\hen-demo\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 25096
hostname: pc1-hz20065563

2019-04-26 13:28:13,141 ERROR 25096 nodejs.ClusterClientNoResponseError: client no response in 90213ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (G:\self-practice\hen-demo\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 25096
hostname: pc1-hz20065563

2019-04-26 13:32:03,950 ERROR 25096 nodejs.ClusterClientNoResponseError: client no response in 90797ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (G:\self-practice\hen-demo\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 25096
hostname: pc1-hz20065563

2019-04-26 13:35:54,169 ERROR 25096 nodejs.ClusterClientNoResponseError: client no response in 90208ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (G:\self-practice\hen-demo\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 25096
hostname: pc1-hz20065563

